spring.application.name=salon-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Brevo REST API
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=kanhaiyadhongade14@gmail.com
brevo.sender.name=SalonBook

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
